### list meilisearch indexes

GET {{MEILISEARCH_HOST}}/indexes

### add meilisearch index

POST {{MEILISEARCH_HOST}}/indexes
Content-Type: application/json

{"uid": "users", "primaryKey": "id"}

### add meilisearch index sortable attribute

PUT {{MEILISEARCH_HOST}}/indexes/users/settings/sortable-attributes
Content-Type: application/json

["name", "email", "status"]

### add meilisearch index filterable attribute

PUT {{MEILISEARCH_HOST}}/indexes/users/settings/filterable-attributes
Content-Type: application/json

["status"]

### add meilisearch document

POST {{MEILISEARCH_HOST}}/indexes/users/documents
Content-Type: application/json

[
  {"id": 1, "email": "johndoe@example.com", "name": "John Doe", "status": "blocked"},
  {"id": 2, "email": "janedoe@example.com", "name": "Jane Doe", "status": "active"}
]

### search meilisearch users
POST {{MEILISEARCH_HOST}}/indexes/users/search
Content-Type: application/json

{
  "sort": ["name:asc"],
  "filter": ["status = active"]
}
